export * from './IFind'
export * from './IFindOne'
export * from './IFindById'
export * from './ISave'
export * from './IUpdateOne'
export * from './IUpdateMany'
export * from './IDeleteOne'
export * from './IDeleteMany'
